language: rust
script: cargo build --features "$CARGO_FEATURES" --verbose && cargo test --verbose
rust:
  - 1.2.0
  - 1.3.0
  - 1.4.0
  - 1.5.0
  - 1.6.0
  - stable
  - beta
  - nightly
matrix:
  allow_failures:
    - rust: nightly
env:
  - CARGO_FEATURES=
matrix:
  include:
    - rust: nightly
      env:
      - CARGO_FEATURES=no_std
branches:
  except:
    - /^issue-.*$/
